# exported from PySB model 'EGFR_MAPK_AKT_STAT'

from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, MultiState, Tag, ANY, WILD

Model()

Monomer('EGF', ['inh'])
Monomer('EGF_ext')
Monomer('EGFR', ['Y1173', 'inh'], {'Y1173': ['u', 'p']})
Monomer('ERBB2', ['Y1248', 'inh'], {'Y1248': ['u', 'p']})
Monomer('iEGFR', ['target'])

Parameter('EGF_degradation_kdeg', 1.0)
Parameter('EGF_eq', 100.0)
Parameter('INPUT_EGF_eq', 0.0)
Parameter('EGF_0', 0.0)
Parameter('EGF_EGF_koff', 0.1)
Parameter('EGF_EGF_kd', 1.0)
Parameter('EGFR_degradation_kdeg', 1.0)
Parameter('EGFR_eq', 100.0)
Parameter('INPUT_EGFR_eq', 0.0)
Parameter('EGFR_phosphorylation_Y1173_base_kcat', 1.0)
Parameter('EGFR_dephosphorylation_Y1173_base_kcat', 1.0)
Parameter('INPUT_EGFR_phosphorylation_Y1173_base_kcat', 0.0)
Parameter('INPUT_EGFR_dephosphorylation_Y1173_base_kcat', 0.0)
Parameter('ERBB2_degradation_kdeg', 1.0)
Parameter('ERBB2_eq', 100.0)
Parameter('INPUT_ERBB2_eq', 0.0)
Parameter('ERBB2_phosphorylation_Y1248_base_kcat', 1.0)
Parameter('ERBB2_dephosphorylation_Y1248_base_kcat', 1.0)
Parameter('INPUT_ERBB2_phosphorylation_Y1248_base_kcat', 0.0)
Parameter('INPUT_ERBB2_dephosphorylation_Y1248_base_kcat', 0.0)
Parameter('EGFR_phosphorylation_Y1173_EGF_kcat', 1.0)
Parameter('INPUT_EGFR_phosphorylation_Y1173_EGF_kcat', 0.0)
Parameter('ERBB2_phosphorylation_Y1248_EGF_kcat', 1.0)
Parameter('INPUT_ERBB2_phosphorylation_Y1248_EGF_kcat', 0.0)
Parameter('iEGFR_0', 0.0)
Parameter('iEGFR_EGFR_koff', 0.1)
Parameter('iEGFR_EGFR_kd', 1.0)

Expression('EGF_synthesis_ksyn', EGF_degradation_kdeg*EGF_eq)
Expression('EGF_synthesis_rate', EGF_synthesis_ksyn*INPUT_EGF_eq)
Expression('EGF_degradation_rate', EGF_degradation_kdeg)
Expression('EGF_ss', EGF_synthesis_rate/EGF_degradation_rate)
Expression('EGF_EGF_kon', EGF_EGF_kd*EGF_EGF_koff)
Expression('EGFR_synthesis_ksyn', EGFR_degradation_kdeg*EGFR_eq)
Expression('EGFR_synthesis_rate', EGFR_synthesis_ksyn*INPUT_EGFR_eq)
Expression('EGFR_degradation_rate', EGFR_degradation_kdeg)
Expression('EGFR_ss', EGFR_synthesis_rate/EGFR_degradation_rate)
Expression('EGFR_phosphorylation_Y1173_base_rate', EGFR_phosphorylation_Y1173_base_kcat*INPUT_EGFR_phosphorylation_Y1173_base_kcat)
Expression('EGFR_dephosphorylation_Y1173_base_rate', EGFR_dephosphorylation_Y1173_base_kcat*INPUT_EGFR_dephosphorylation_Y1173_base_kcat)
Expression('ERBB2_synthesis_ksyn', ERBB2_degradation_kdeg*ERBB2_eq)
Expression('ERBB2_synthesis_rate', ERBB2_synthesis_ksyn*INPUT_ERBB2_eq)
Expression('ERBB2_degradation_rate', ERBB2_degradation_kdeg)
Expression('ERBB2_ss', ERBB2_synthesis_rate/ERBB2_degradation_rate)
Expression('ERBB2_phosphorylation_Y1248_base_rate', ERBB2_phosphorylation_Y1248_base_kcat*INPUT_ERBB2_phosphorylation_Y1248_base_kcat)
Expression('ERBB2_dephosphorylation_Y1248_base_rate', ERBB2_dephosphorylation_Y1248_base_kcat*INPUT_ERBB2_dephosphorylation_Y1248_base_kcat)
Expression('iEGFR_EGFR_kon', iEGFR_EGFR_kd*iEGFR_EGFR_koff)

Observable('EGF_obs', EGF(inh=None))
Observable('tEGF', EGF())
Observable('tEGF_ext', EGF_ext())
Observable('tEGFR', EGFR())
Observable('pEGFR_Y1173', EGFR(Y1173='p'))
Observable('tERBB2', ERBB2())
Observable('pERBB2_Y1248', ERBB2(Y1248='p'))
Observable('tiEGFR', iEGFR())

Expression('EGFR_phosphorylation_Y1173_EGF_rate', EGF_obs*EGFR_phosphorylation_Y1173_EGF_kcat*INPUT_EGFR_phosphorylation_Y1173_EGF_kcat)
Expression('ERBB2_phosphorylation_Y1248_EGF_rate', EGF_obs*ERBB2_phosphorylation_Y1248_EGF_kcat*INPUT_ERBB2_phosphorylation_Y1248_EGF_kcat)

Rule('synthesis_EGF', None >> EGF(inh=None), EGF_synthesis_rate)
Rule('degradation_EGF', EGF() >> None, EGF_degradation_rate)
Rule('EGF_ext_to_EGF', EGF_ext() | EGF(inh=None), EGF_EGF_kon, EGF_EGF_koff)
Rule('synthesis_EGFR', None >> EGFR(Y1173='u', inh=None), EGFR_synthesis_rate)
Rule('degradation_EGFR', EGFR() >> None, EGFR_degradation_rate)
Rule('EGFR_Y1173_base', EGFR(Y1173='p') | EGFR(Y1173='u'), EGFR_phosphorylation_Y1173_base_rate, EGFR_dephosphorylation_Y1173_base_rate)
Rule('synthesis_ERBB2', None >> ERBB2(Y1248='u', inh=None), ERBB2_synthesis_rate)
Rule('degradation_ERBB2', ERBB2() >> None, ERBB2_degradation_rate)
Rule('ERBB2_Y1248_base', ERBB2(Y1248='p') | ERBB2(Y1248='u'), ERBB2_phosphorylation_Y1248_base_rate, ERBB2_dephosphorylation_Y1248_base_rate)
Rule('EGFR_phosphorylation_Y1173_EGF', EGFR(Y1173='u') >> EGFR(Y1173='p'), EGFR_phosphorylation_Y1173_EGF_rate)
Rule('ERBB2_phosphorylation_Y1248_EGF', ERBB2(Y1248='u') >> ERBB2(Y1248='p'), ERBB2_phosphorylation_Y1248_EGF_rate)
Rule('iEGFR_inhibits_EGFR', EGFR(inh=None) + iEGFR(target=None) | EGFR(inh=1) % iEGFR(target=1), iEGFR_EGFR_kon, iEGFR_EGFR_koff)

Initial(EGF(inh=None), EGF_ss)
Initial(EGF_ext(), EGF_0, fixed=True)
Initial(EGFR(Y1173='u', inh=None), EGFR_ss)
Initial(ERBB2(Y1248='u', inh=None), ERBB2_ss)
Initial(iEGFR(target=None), iEGFR_0, fixed=True)

