---
title: 'Create Parameter Files and Folders for CausalPath Analysis'
author: "Will Yashar"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    number_sections: no
    theme: lumen
    toc: yes
    toc_float:
      collapsed: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Packages
```{r}
library(tidyverse)
```

# Load data

```{r}
cp_format_file <- "aml_data_cp_format_row_norm.tsv"
data <- read.table(file = cp_format_file, sep = "\t", header = TRUE, check.names = FALSE)
metadata <- read.table(file = "metadata.tsv", sep = "\t", header = TRUE)
```

# Harmonize metadata

```{r}
# Control
metadata$treatment[metadata$treatment == "No treatment"] <- "none"
metadata$treatment[metadata$treatment == "no treatment"] <- "none"
metadata$treatment[metadata$treatment == "DMSO"] <- "none"

# Trametinib
metadata$treatment[metadata$treatment == "trametinib"] <- "Trametinib"

# Ruxolitnib
metadata$treatment[metadata$treatment == "ruxolitnib"] <- "Ruxolitnib"

# Dasatinib
metadata$treatment[metadata$treatment == "dasatinib"] <- "Dasatinib"

# Sorafenib
metadata$treatment[metadata$treatment == "sorafenib"] <- "Sorafenib"

# Trametinib Withdrawn
metadata$treatment[metadata$treatment == "Trametinib Withdrawn"] <- "Trametinib_Withdrawn"
```

# Identify comparison groups
# MOLM-13
```{r}
# Store experiments
exptsList <- list()

## Cell Line
cellLine <- "MOLM-13"

### Control
tx <- "none"
values <- metadata[( (metadata$cellLine == cellLine) & (metadata$treatment == tx) ), "sample"]
exptsList[[cellLine]][[tx]] <- list(values)

### Trametinib
tx <- "Trametinib"
timePoints <- unique(metadata[( (metadata$cellLine == cellLine) & (metadata$treatment == tx) ), "timePoint"])

for (time in timePoints) {
  values <- metadata[( (grepl(cellLine, metadata$cellLine) == TRUE) & (metadata$treatment == tx) & (metadata$timePoint == time) ), "sample"]
  exptsList[[cellLine]][[tx]][time] <- list(values)
}

### MCP-1
tx <- "MCP-1"
timePoints <- unique(metadata[( (metadata$cellLine == cellLine) & (metadata$treatment == tx) ), "timePoint"])

for (time in timePoints) {
  values <- metadata[( (grepl(cellLine, metadata$cellLine) == TRUE) & (metadata$treatment == tx) & (metadata$timePoint == time) ), "sample"]
  exptsList[[cellLine]][[tx]][time] <- list(values)
}

### Trametinib+MCP-1
tx <- "Trametinib+MCP-1"
timePoints <- unique(metadata[( (metadata$cellLine == cellLine) & (metadata$treatment == tx) ), "timePoint"])

for (time in timePoints) {
  values <- metadata[( (grepl(cellLine, metadata$cellLine) == TRUE) & (metadata$treatment == tx) & (metadata$timePoint == time) ), "sample"]
  exptsList[[cellLine]][[tx]][time] <- list(values)
}
```

# Identify comparison groups
# MOLM-14-a
```{r}
## Cell Line
cellLine <- "MOLM14-a"

### Control
tx <- "none"
values <- metadata[( (metadata$cellLine == cellLine) & (metadata$treatment == tx) ), "sample"]
exptsList[[cellLine]][[tx]] <- list(values)

### Gilteritinib
tx <- "Gilteritinib"
timePoints <- unique(metadata[( (metadata$cellLine == cellLine) & (metadata$treatment == tx) ), "timePoint"])

for (time in timePoints) {
  values <- metadata[( (grepl(cellLine, metadata$cellLine) == TRUE) & (metadata$treatment == tx) & (metadata$timePoint == time) ), "sample"]
  exptsList[[cellLine]][[tx]][time] <- list(values)
}
```

# Identify comparison groups
# MOLM-14-b
```{r}
## Cell Line
cellLine <- "MOLM14-b"

### Control
tx <- "none"
values <- metadata[( (metadata$cellLine == cellLine) & (metadata$treatment == tx) ), "sample"]
exptsList[[cellLine]][[tx]] <- list(values)

### Gilteritinib
tx <- "Gilteritinib"
timePoints <- unique(metadata[( (metadata$cellLine == cellLine) & (metadata$treatment == tx) ), "timePoint"])

for (time in timePoints) {
  values <- metadata[( (grepl(cellLine, metadata$cellLine) == TRUE) & (metadata$treatment == tx) & (metadata$timePoint == time) ), "sample"]
  exptsList[[cellLine]][[tx]][time] <- list(values)
}
```

# Identify comparison groups
# MOLM-14
```{r}
## Cell Line
cellLine <- "MOLM14"

### Control
tx <- "none"
values <- metadata[( (grepl(cellLine, metadata$cellLine) == TRUE) & (metadata$treatment == tx) ), "sample"]
exptsList[[cellLine]][[tx]] <- list(values)

### Gilteritinib
tx <- "Gilteritinib"
timePoints <- unique(metadata[( (grepl(cellLine, metadata$cellLine) == TRUE) & (metadata$treatment == tx) ), "timePoint"])

for (time in timePoints) {
  values <- metadata[( (grepl(cellLine, metadata$cellLine) == TRUE) & (metadata$treatment == tx) & (metadata$timePoint == time) ), "sample"]
  exptsList[[cellLine]][[tx]][time] <- list(values)
}
```

# Create parameters file
```{r}

for (cell in names(exptsList)) {

  for (tx in names(exptsList[[cell]])) {

    for (time in names(exptsList[[cell]][[tx]])) {

      # create directory
      dir_path <- sprintf("results/%s/%s/%s", cell, tx, time)
      dir.create(path = dir_path, showWarnings = FALSE, recursive = TRUE)

      # Set parameters
      # parameters = c(paste0("proteomics-values-file = ", cp_format_file),
      #                "id-column = ID",
      #                "symbols-column = Symbols",
      #                "sites-column = Sites",
      #                "effect-column = Effect",
      #                "value-transformation = significant-change-of-mean",
      #                "fdr-threshold-for-data-significance = 0.1 phosphoprotein",
      #                "fdr-threshold-for-data-significance = 0.1 protein",
      #                "calculate-network-significance = true",
      #                "permutations-for-significance = 100",
      #                "generate-data-centric-graph = false",
      #                "show-insignificant-data = false",
      #                "color-saturation-value = 50",
      #                "custom-resource-directory = /Users/yashar/gitPackages/causalpath/.panda",
      #                "use-network-significance-for-causal-reasoning = false")

      parameters = c(paste0("proteomics-values-file = ", cp_format_file),
                 "id-column = ID",
                 "symbols-column = Symbols",
                 "sites-column = Sites",
                 "effect-column = Effect",
                 "value-transformation = fold-change-of-mean",
                 "threshold-for-data-significance = 2.5 phosphoprotein",
                 "threshold-for-data-significance = 2.5 protein",
                 "calculate-network-significance = true",
                 "permutations-for-significance = 100",
                 "generate-data-centric-graph = false",
                 "show-insignificant-data = false",
                 "color-saturation-value = 50",
                 "custom-resource-directory = /Users/yashar/gitPackages/causalpath/.panda",
                 "use-network-significance-for-causal-reasoning = false")
      
      

      # Set control values
      i <- length(parameters)
      for (control in unlist(exptsList[[cell]][['none']][[1]])) {
        i <- i + 1
        parameters[i] <- paste0("control-value-column = ", control)
      }

      # Set test columns
      for (test in unlist(exptsList[[cell]][[tx]][time])) {
        i <- i + 1
        parameters[i] <- paste0("test-value-column = ", test)
      }

      # Write to parameters file
      file_path <- file(sprintf("%s/parameters.txt", dir_path))
      writeLines(parameters, file_path)
      close(file_path)

      # Save Causal Path File
      write.table(data, file = sprintf("%s/%s", dir_path, cp_format_file), sep = "\t", row.names = FALSE, quote = FALSE)

    }
    
  }
  
}
```

# All Iterations
# Pool all controls together
```{r}
# Store experiments
exptsList <- list()

## Cell Line
cellLine <- "all"

### Control
tx <- "none"
values <- metadata[(metadata$treatment == tx), "sample"]
exptsList[[cellLine]][[tx]] <- list(values)

### All treatments
txs <- unique(metadata[, "treatment"])
txs <- txs[( (txs != "none") & (txs != NaN) )]

for (tx in txs) {
  
  timePoints <- unique(metadata[( (metadata$treatment == tx) ), "timePoint"])

  for (time in timePoints) {
    values <- metadata[( (metadata$treatment == tx) & (metadata$timePoint == time) ), "sample"]
    exptsList[[cellLine]][[tx]][time] <- list(values)
  }
  
}

```

# Create parameters file
```{r}

for (cell in names(exptsList)) {

  for (tx in names(exptsList[[cell]])) {

    for (time in names(exptsList[[cell]][[tx]])) {

      # create directory
      dir_path <- sprintf("results/%s/%s/%s", cell, tx, time)
      dir.create(path = dir_path, showWarnings = FALSE, recursive = TRUE)

      # Set parameters
      # parameters = c(paste0("proteomics-values-file = ", cp_format_file),
      #            "id-column = ID",
      #            "symbols-column = Symbols",
      #            "sites-column = Sites",
      #            "effect-column = Effect",
      #            "value-transformation = significant-change-of-mean",
      #            "fdr-threshold-for-data-significance = 0.1 phosphoprotein",
      #            "fdr-threshold-for-data-significance = 0.1 protein",
      #            "calculate-network-significance = true",
      #            "permutations-for-significance = 100",
      #            "generate-data-centric-graph = false",
      #            "show-insignificant-data = false",
      #            "color-saturation-value = 50",
      #            "custom-resource-directory = /Users/yashar/gitPackages/causalpath/.panda",
      #            "use-network-significance-for-causal-reasoning = false")
      
      parameters = c(paste0("proteomics-values-file = ", cp_format_file),
                 "id-column = ID",
                 "symbols-column = Symbols",
                 "sites-column = Sites",
                 "effect-column = Effect",
                 "value-transformation = fold-change-of-mean",
                 "threshold-for-data-significance = 2.5 phosphoprotein",
                 "threshold-for-data-significance = 2.5 protein",
                 "calculate-network-significance = true",
                 "permutations-for-significance = 100",
                 "generate-data-centric-graph = false",
                 "show-insignificant-data = false",
                 "color-saturation-value = 50",
                 "custom-resource-directory = /Users/yashar/gitPackages/causalpath/.panda",
                 "use-network-significance-for-causal-reasoning = false")

      # Set control values
      i <- length(parameters)
      for (control in unlist(exptsList[[cell]][['none']][[1]])) {
        i <- i + 1
        parameters[i] <- paste0("control-value-column = ", control)
      }

      # Set test columns
      for (test in unlist(exptsList[[cell]][[tx]][time])) {
        i <- i + 1
        parameters[i] <- paste0("test-value-column = ", test)
      }

      # Write to parameters file
      file_path <- file(sprintf("%s/parameters.txt", dir_path))
      writeLines(parameters, file_path)
      close(file_path)

      # Save Causal Path File
      write.table(data, file = sprintf("%s/%s", dir_path, cp_format_file), sep = "\t", row.names = FALSE, quote = FALSE)

    }
    
  }
  
}
```

# Session Information

```{r}
sessionInfo()
```