---
title: 'Create metadata file'
author: "Will Yashar"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    number_sections: no
    theme: lumen
    toc: yes
    toc_float:
      collapsed: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Packages
```{r}
library(tidyverse)
```

# Load data
```{r}
data <- read.csv("data/combinedPhosphoData.tsv", sep='\t')
```

# Create Metadata File
```{r}
# Identify unique samples
samples <- unique(data$sample)

#Initialize metadata file
metadata <- data.frame(matrix(nrow = length(samples), ncol = 4))
colnames(metadata) <- c("sample", "timePoint", "treatment", "cellLine")
metadata$sample <- samples

# Extract metadata values for each sample
for (sample in samples) {
  # Extract values
  timePoint <- data[data$sample == sample, "timePoint"][1]
  treatment <- data[data$sample == sample, "treatment"][1]
  cellLine <- data[data$sample == sample, "cellLine"][1]
  
  # Save in metadata file
  metadata[metadata$sample == sample, "timePoint"] <- timePoint
  metadata[metadata$sample == sample, "treatment"] <- treatment
  metadata[metadata$sample == sample, "cellLine"] <- cellLine
}
```

# Save
```{r}
# Sort
metadata <- metadata %>% 
  arrange(timePoint, treatment, cellLine)

# Save
write.table(metadata, "metadata.tsv", sep = "\t", row.names = FALSE)
```

```{r}
Sys.info()
```