name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup submodule
      run: git submodule update --init --recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pylint
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --cov=mEncoder --cov-report=xml
    - name: Lint with pylint
      run: pylint --rcfile=./common/pylintrc --fail-under=9 mEncoder
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
