name: Test

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup submodule
      run: git submodule update --init --recursive
    - name: Install environment
      run: make venv
    - name: Test with pytest
      run: make coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
    - name: Dryrun Snakemake
      run: . venv/bin/activate && snakemake -n collect_estimation --config num_starts=2 --verbose
