name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup submodule
      run: git submodule update --init --recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install BNGL
      run: |
        wget -q -O bionetgen.tar.gz https://github.com/RuleWorld/bionetgen/releases/download/BioNetGen-2.5.1/BioNetGen-2.5.1-linux.tgz
        tar -xzf bionetgen.tar.gz
        echo "::set-env name=BNGPATH::$(pwd)/BioNetGen-2.5.1"
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          swig \
          libatlas-base-dev \
          libhdf5-serial-dev \
          libboost-math-dev
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pylint
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --cov=mEncoder --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Dryrun Snakemake
      run: |
        pip install snakemake
        snakemake -n collect_estimation --config num_starts=2 --verbose
